### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by de-vri-es** [rust-embedded/rust-spidev#14]
Could I politely ask if we can get a 0.3.1 release? The project seems quite stable (which makes sense), but it could be a while for the next change to land. So waiting for more changes might not make sense.

I'd really like to use #13 without specifying the dependency from git :)

**Comment by posborne** [comment]
0.4.0 is now published.  Sorry for the long delays and lack of activity for quite some time.

**Comment by de-vri-es** [comment]
No problem, thanks for the release! :tada:
