### ISSUE TITLE
Tag 0.4.0 release

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/rust-spidev#21]
I noticed that the tag of the 0.4.0 release is missing. See [releases](https://github.com/rust-embedded/rust-spidev/releases).
Maybe pushing it was forgotten?

**Comment by posborne** [comment]
> I noticed that the tag of the 0.4.0 release is missing. See releases.  Maybe pushing it was forgotten?

Thank you, I did forget to push it.  Pushed now at the appropriate commit.
