### ISSUE TITLE
Providing support for Longan Nano board

### ISSUE THREAD

**Issue by advancedwebdeveloper** [rust-embedded/rust-spidev#24]
I am curious about the required steps for building demos apps, which would target https://longan.sipeed.com/en/ board.

CC @joba-1 , in case if you are curious to migrate https://github.com/joba-1/Longan-Nano-Bme280-Spi to Rust.

**Comment by joba-1** [comment]
Thanks for the headsup (and for the indication someone else actually looks at my stuff).
It is unlikely though that I dive in to yet another programming language for this. There is enough to explore on the nano itself and I still struggle a bit to find a real usecase for it

**Comment by barafael** [comment]
This crate is for spi in Linux. The nano does not run Linux. @eldruin I think this issue can be closed.

**Comment by eldruin** [comment]
Thanks @barafael!
