### ISSUE TITLE
Use GitHub Actions instead of Travis for CI

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/rust-spidev#28]
- [ ] Use GHA
- [ ] Add bors configuration
- [ ] Setup branch protection

**Comment by ryankurte** [comment]
Good call, looks like there might be something missing with bors / branch protection too given https://github.com/rust-embedded/rust-spidev/pull/27 merged via web interface?

**Comment by eldruin** [comment]
Yes, that is also true.
