### ISSUE TITLE
Implement embedded_hal::spi Traits

### ISSUE THREAD

**Issue by alexkl-rugged-controls** [rust-embedded/rust-spidev#44]
Now that embedded_hal has reached 1.0 - would it be possible to unify the traits against embedded_hal::spi?

**Comment by ryankurte** [comment]
`spidev` is just a rust implementation of the linux spidev APIs, you might be looking for [linux-embedded-hal](https://docs.rs/linux-embedded-hal/latest/linux_embedded_hal/) which provides embedded-hal compatible wrappers?

**Comment by alexkl-rugged-controls** [comment]
Huh, apologies! That's exactly what I want.
